import { createRouter } from '@tanstack/react-router'
// routeTree.gen.ts is auto-generated by the TanStack Router Vite plugin.
// Run `npm run dev` once to generate it before running `npm run typecheck` or `npm run build`.
import { routeTree } from './routeTree.gen'

export const router = createRouter({ routeTree })

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}
