/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthSheetsIndexRouteImport } from './routes/_auth/sheets/index'
import { Route as AuthSheetsSheetIdRouteImport } from './routes/_auth/sheets/$sheetId'
import { Route as AuthSheetsSheetIdIndexRouteImport } from './routes/_auth/sheets/$sheetId/index'
import { Route as AuthSheetsSheetIdTransactionFormRouteImport } from './routes/_auth/sheets/$sheetId/transaction-form'
import { Route as AuthSheetsSheetIdSettingsRouteImport } from './routes/_auth/sheets/$sheetId/settings'
import { Route as AuthSheetsSheetIdDashboardRouteImport } from './routes/_auth/sheets/$sheetId/dashboard'
import { Route as AuthSheetsSheetIdCategoryCategoryIdRouteImport } from './routes/_auth/sheets/$sheetId/category/$categoryId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSheetsIndexRoute = AuthSheetsIndexRouteImport.update({
  id: '/sheets/',
  path: '/sheets/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSheetsSheetIdRoute = AuthSheetsSheetIdRouteImport.update({
  id: '/sheets/$sheetId',
  path: '/sheets/$sheetId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSheetsSheetIdIndexRoute = AuthSheetsSheetIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSheetsSheetIdRoute,
} as any)
const AuthSheetsSheetIdTransactionFormRoute =
  AuthSheetsSheetIdTransactionFormRouteImport.update({
    id: '/transaction-form',
    path: '/transaction-form',
    getParentRoute: () => AuthSheetsSheetIdRoute,
  } as any)
const AuthSheetsSheetIdSettingsRoute =
  AuthSheetsSheetIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthSheetsSheetIdRoute,
  } as any)
const AuthSheetsSheetIdDashboardRoute =
  AuthSheetsSheetIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthSheetsSheetIdRoute,
  } as any)
const AuthSheetsSheetIdCategoryCategoryIdRoute =
  AuthSheetsSheetIdCategoryCategoryIdRouteImport.update({
    id: '/category/$categoryId',
    path: '/category/$categoryId',
    getParentRoute: () => AuthSheetsSheetIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/sheets/$sheetId': typeof AuthSheetsSheetIdRouteWithChildren
  '/sheets/': typeof AuthSheetsIndexRoute
  '/sheets/$sheetId/dashboard': typeof AuthSheetsSheetIdDashboardRoute
  '/sheets/$sheetId/settings': typeof AuthSheetsSheetIdSettingsRoute
  '/sheets/$sheetId/transaction-form': typeof AuthSheetsSheetIdTransactionFormRoute
  '/sheets/$sheetId/': typeof AuthSheetsSheetIdIndexRoute
  '/sheets/$sheetId/category/$categoryId': typeof AuthSheetsSheetIdCategoryCategoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/sheets': typeof AuthSheetsIndexRoute
  '/sheets/$sheetId/dashboard': typeof AuthSheetsSheetIdDashboardRoute
  '/sheets/$sheetId/settings': typeof AuthSheetsSheetIdSettingsRoute
  '/sheets/$sheetId/transaction-form': typeof AuthSheetsSheetIdTransactionFormRoute
  '/sheets/$sheetId': typeof AuthSheetsSheetIdIndexRoute
  '/sheets/$sheetId/category/$categoryId': typeof AuthSheetsSheetIdCategoryCategoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_auth/sheets/$sheetId': typeof AuthSheetsSheetIdRouteWithChildren
  '/_auth/sheets/': typeof AuthSheetsIndexRoute
  '/_auth/sheets/$sheetId/dashboard': typeof AuthSheetsSheetIdDashboardRoute
  '/_auth/sheets/$sheetId/settings': typeof AuthSheetsSheetIdSettingsRoute
  '/_auth/sheets/$sheetId/transaction-form': typeof AuthSheetsSheetIdTransactionFormRoute
  '/_auth/sheets/$sheetId/': typeof AuthSheetsSheetIdIndexRoute
  '/_auth/sheets/$sheetId/category/$categoryId': typeof AuthSheetsSheetIdCategoryCategoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/auth/callback'
    | '/sheets/$sheetId'
    | '/sheets/'
    | '/sheets/$sheetId/dashboard'
    | '/sheets/$sheetId/settings'
    | '/sheets/$sheetId/transaction-form'
    | '/sheets/$sheetId/'
    | '/sheets/$sheetId/category/$categoryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/auth/callback'
    | '/sheets'
    | '/sheets/$sheetId/dashboard'
    | '/sheets/$sheetId/settings'
    | '/sheets/$sheetId/transaction-form'
    | '/sheets/$sheetId'
    | '/sheets/$sheetId/category/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/signup'
    | '/auth/callback'
    | '/_auth/sheets/$sheetId'
    | '/_auth/sheets/'
    | '/_auth/sheets/$sheetId/dashboard'
    | '/_auth/sheets/$sheetId/settings'
    | '/_auth/sheets/$sheetId/transaction-form'
    | '/_auth/sheets/$sheetId/'
    | '/_auth/sheets/$sheetId/category/$categoryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sheets/': {
      id: '/_auth/sheets/'
      path: '/sheets'
      fullPath: '/sheets/'
      preLoaderRoute: typeof AuthSheetsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sheets/$sheetId': {
      id: '/_auth/sheets/$sheetId'
      path: '/sheets/$sheetId'
      fullPath: '/sheets/$sheetId'
      preLoaderRoute: typeof AuthSheetsSheetIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sheets/$sheetId/': {
      id: '/_auth/sheets/$sheetId/'
      path: '/'
      fullPath: '/sheets/$sheetId/'
      preLoaderRoute: typeof AuthSheetsSheetIdIndexRouteImport
      parentRoute: typeof AuthSheetsSheetIdRoute
    }
    '/_auth/sheets/$sheetId/transaction-form': {
      id: '/_auth/sheets/$sheetId/transaction-form'
      path: '/transaction-form'
      fullPath: '/sheets/$sheetId/transaction-form'
      preLoaderRoute: typeof AuthSheetsSheetIdTransactionFormRouteImport
      parentRoute: typeof AuthSheetsSheetIdRoute
    }
    '/_auth/sheets/$sheetId/settings': {
      id: '/_auth/sheets/$sheetId/settings'
      path: '/settings'
      fullPath: '/sheets/$sheetId/settings'
      preLoaderRoute: typeof AuthSheetsSheetIdSettingsRouteImport
      parentRoute: typeof AuthSheetsSheetIdRoute
    }
    '/_auth/sheets/$sheetId/dashboard': {
      id: '/_auth/sheets/$sheetId/dashboard'
      path: '/dashboard'
      fullPath: '/sheets/$sheetId/dashboard'
      preLoaderRoute: typeof AuthSheetsSheetIdDashboardRouteImport
      parentRoute: typeof AuthSheetsSheetIdRoute
    }
    '/_auth/sheets/$sheetId/category/$categoryId': {
      id: '/_auth/sheets/$sheetId/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/sheets/$sheetId/category/$categoryId'
      preLoaderRoute: typeof AuthSheetsSheetIdCategoryCategoryIdRouteImport
      parentRoute: typeof AuthSheetsSheetIdRoute
    }
  }
}

interface AuthSheetsSheetIdRouteChildren {
  AuthSheetsSheetIdDashboardRoute: typeof AuthSheetsSheetIdDashboardRoute
  AuthSheetsSheetIdSettingsRoute: typeof AuthSheetsSheetIdSettingsRoute
  AuthSheetsSheetIdTransactionFormRoute: typeof AuthSheetsSheetIdTransactionFormRoute
  AuthSheetsSheetIdIndexRoute: typeof AuthSheetsSheetIdIndexRoute
  AuthSheetsSheetIdCategoryCategoryIdRoute: typeof AuthSheetsSheetIdCategoryCategoryIdRoute
}

const AuthSheetsSheetIdRouteChildren: AuthSheetsSheetIdRouteChildren = {
  AuthSheetsSheetIdDashboardRoute: AuthSheetsSheetIdDashboardRoute,
  AuthSheetsSheetIdSettingsRoute: AuthSheetsSheetIdSettingsRoute,
  AuthSheetsSheetIdTransactionFormRoute: AuthSheetsSheetIdTransactionFormRoute,
  AuthSheetsSheetIdIndexRoute: AuthSheetsSheetIdIndexRoute,
  AuthSheetsSheetIdCategoryCategoryIdRoute:
    AuthSheetsSheetIdCategoryCategoryIdRoute,
}

const AuthSheetsSheetIdRouteWithChildren =
  AuthSheetsSheetIdRoute._addFileChildren(AuthSheetsSheetIdRouteChildren)

interface AuthRouteChildren {
  AuthSheetsSheetIdRoute: typeof AuthSheetsSheetIdRouteWithChildren
  AuthSheetsIndexRoute: typeof AuthSheetsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSheetsSheetIdRoute: AuthSheetsSheetIdRouteWithChildren,
  AuthSheetsIndexRoute: AuthSheetsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
