/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthSheetsIndexRouteImport } from './routes/_auth/sheets/index'
import { Route as AuthSheetsSheetIdRouteImport } from './routes/_auth/sheets/$sheetId'
import { Route as AuthSheetsSheetIdIndexRouteImport } from './routes/_auth/sheets/$sheetId/index'
import { Route as AuthSheetsSheetIdTransactionFormRouteImport } from './routes/_auth/sheets/$sheetId/transaction-form'
import { Route as AuthSheetsSheetIdSettingsRouteImport } from './routes/_auth/sheets/$sheetId/settings'
import { Route as AuthSheetsSheetIdOverviewIndexRouteImport } from './routes/_auth/sheets/$sheetId/overview/index'
import { Route as AuthSheetsSheetIdOverviewCategoryIdIndexRouteImport } from './routes/_auth/sheets/$sheetId/overview/$categoryId/index'
import { Route as AuthSheetsSheetIdOverviewCategoryIdEditRouteImport } from './routes/_auth/sheets/$sheetId/overview/$categoryId/edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSheetsIndexRoute = AuthSheetsIndexRouteImport.update({
  id: '/sheets/',
  path: '/sheets/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSheetsSheetIdRoute = AuthSheetsSheetIdRouteImport.update({
  id: '/sheets/$sheetId',
  path: '/sheets/$sheetId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSheetsSheetIdIndexRoute = AuthSheetsSheetIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSheetsSheetIdRoute,
} as any)
const AuthSheetsSheetIdTransactionFormRoute =
  AuthSheetsSheetIdTransactionFormRouteImport.update({
    id: '/transaction-form',
    path: '/transaction-form',
    getParentRoute: () => AuthSheetsSheetIdRoute,
  } as any)
const AuthSheetsSheetIdSettingsRoute =
  AuthSheetsSheetIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthSheetsSheetIdRoute,
  } as any)
const AuthSheetsSheetIdOverviewIndexRoute =
  AuthSheetsSheetIdOverviewIndexRouteImport.update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => AuthSheetsSheetIdRoute,
  } as any)
const AuthSheetsSheetIdOverviewCategoryIdIndexRoute =
  AuthSheetsSheetIdOverviewCategoryIdIndexRouteImport.update({
    id: '/overview/$categoryId/',
    path: '/overview/$categoryId/',
    getParentRoute: () => AuthSheetsSheetIdRoute,
  } as any)
const AuthSheetsSheetIdOverviewCategoryIdEditRoute =
  AuthSheetsSheetIdOverviewCategoryIdEditRouteImport.update({
    id: '/overview/$categoryId/edit',
    path: '/overview/$categoryId/edit',
    getParentRoute: () => AuthSheetsSheetIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/sheets/$sheetId': typeof AuthSheetsSheetIdRouteWithChildren
  '/sheets/': typeof AuthSheetsIndexRoute
  '/sheets/$sheetId/settings': typeof AuthSheetsSheetIdSettingsRoute
  '/sheets/$sheetId/transaction-form': typeof AuthSheetsSheetIdTransactionFormRoute
  '/sheets/$sheetId/': typeof AuthSheetsSheetIdIndexRoute
  '/sheets/$sheetId/overview/': typeof AuthSheetsSheetIdOverviewIndexRoute
  '/sheets/$sheetId/overview/$categoryId/edit': typeof AuthSheetsSheetIdOverviewCategoryIdEditRoute
  '/sheets/$sheetId/overview/$categoryId/': typeof AuthSheetsSheetIdOverviewCategoryIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/sheets': typeof AuthSheetsIndexRoute
  '/sheets/$sheetId/settings': typeof AuthSheetsSheetIdSettingsRoute
  '/sheets/$sheetId/transaction-form': typeof AuthSheetsSheetIdTransactionFormRoute
  '/sheets/$sheetId': typeof AuthSheetsSheetIdIndexRoute
  '/sheets/$sheetId/overview': typeof AuthSheetsSheetIdOverviewIndexRoute
  '/sheets/$sheetId/overview/$categoryId/edit': typeof AuthSheetsSheetIdOverviewCategoryIdEditRoute
  '/sheets/$sheetId/overview/$categoryId': typeof AuthSheetsSheetIdOverviewCategoryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_auth/sheets/$sheetId': typeof AuthSheetsSheetIdRouteWithChildren
  '/_auth/sheets/': typeof AuthSheetsIndexRoute
  '/_auth/sheets/$sheetId/settings': typeof AuthSheetsSheetIdSettingsRoute
  '/_auth/sheets/$sheetId/transaction-form': typeof AuthSheetsSheetIdTransactionFormRoute
  '/_auth/sheets/$sheetId/': typeof AuthSheetsSheetIdIndexRoute
  '/_auth/sheets/$sheetId/overview/': typeof AuthSheetsSheetIdOverviewIndexRoute
  '/_auth/sheets/$sheetId/overview/$categoryId/edit': typeof AuthSheetsSheetIdOverviewCategoryIdEditRoute
  '/_auth/sheets/$sheetId/overview/$categoryId/': typeof AuthSheetsSheetIdOverviewCategoryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/auth/callback'
    | '/sheets/$sheetId'
    | '/sheets/'
    | '/sheets/$sheetId/settings'
    | '/sheets/$sheetId/transaction-form'
    | '/sheets/$sheetId/'
    | '/sheets/$sheetId/overview/'
    | '/sheets/$sheetId/overview/$categoryId/edit'
    | '/sheets/$sheetId/overview/$categoryId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/auth/callback'
    | '/sheets'
    | '/sheets/$sheetId/settings'
    | '/sheets/$sheetId/transaction-form'
    | '/sheets/$sheetId'
    | '/sheets/$sheetId/overview'
    | '/sheets/$sheetId/overview/$categoryId/edit'
    | '/sheets/$sheetId/overview/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/signup'
    | '/auth/callback'
    | '/_auth/sheets/$sheetId'
    | '/_auth/sheets/'
    | '/_auth/sheets/$sheetId/settings'
    | '/_auth/sheets/$sheetId/transaction-form'
    | '/_auth/sheets/$sheetId/'
    | '/_auth/sheets/$sheetId/overview/'
    | '/_auth/sheets/$sheetId/overview/$categoryId/edit'
    | '/_auth/sheets/$sheetId/overview/$categoryId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sheets/': {
      id: '/_auth/sheets/'
      path: '/sheets'
      fullPath: '/sheets/'
      preLoaderRoute: typeof AuthSheetsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sheets/$sheetId': {
      id: '/_auth/sheets/$sheetId'
      path: '/sheets/$sheetId'
      fullPath: '/sheets/$sheetId'
      preLoaderRoute: typeof AuthSheetsSheetIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sheets/$sheetId/': {
      id: '/_auth/sheets/$sheetId/'
      path: '/'
      fullPath: '/sheets/$sheetId/'
      preLoaderRoute: typeof AuthSheetsSheetIdIndexRouteImport
      parentRoute: typeof AuthSheetsSheetIdRoute
    }
    '/_auth/sheets/$sheetId/transaction-form': {
      id: '/_auth/sheets/$sheetId/transaction-form'
      path: '/transaction-form'
      fullPath: '/sheets/$sheetId/transaction-form'
      preLoaderRoute: typeof AuthSheetsSheetIdTransactionFormRouteImport
      parentRoute: typeof AuthSheetsSheetIdRoute
    }
    '/_auth/sheets/$sheetId/settings': {
      id: '/_auth/sheets/$sheetId/settings'
      path: '/settings'
      fullPath: '/sheets/$sheetId/settings'
      preLoaderRoute: typeof AuthSheetsSheetIdSettingsRouteImport
      parentRoute: typeof AuthSheetsSheetIdRoute
    }
    '/_auth/sheets/$sheetId/overview/': {
      id: '/_auth/sheets/$sheetId/overview/'
      path: '/overview'
      fullPath: '/sheets/$sheetId/overview/'
      preLoaderRoute: typeof AuthSheetsSheetIdOverviewIndexRouteImport
      parentRoute: typeof AuthSheetsSheetIdRoute
    }
    '/_auth/sheets/$sheetId/overview/$categoryId/': {
      id: '/_auth/sheets/$sheetId/overview/$categoryId/'
      path: '/overview/$categoryId'
      fullPath: '/sheets/$sheetId/overview/$categoryId/'
      preLoaderRoute: typeof AuthSheetsSheetIdOverviewCategoryIdIndexRouteImport
      parentRoute: typeof AuthSheetsSheetIdRoute
    }
    '/_auth/sheets/$sheetId/overview/$categoryId/edit': {
      id: '/_auth/sheets/$sheetId/overview/$categoryId/edit'
      path: '/overview/$categoryId/edit'
      fullPath: '/sheets/$sheetId/overview/$categoryId/edit'
      preLoaderRoute: typeof AuthSheetsSheetIdOverviewCategoryIdEditRouteImport
      parentRoute: typeof AuthSheetsSheetIdRoute
    }
  }
}

interface AuthSheetsSheetIdRouteChildren {
  AuthSheetsSheetIdSettingsRoute: typeof AuthSheetsSheetIdSettingsRoute
  AuthSheetsSheetIdTransactionFormRoute: typeof AuthSheetsSheetIdTransactionFormRoute
  AuthSheetsSheetIdIndexRoute: typeof AuthSheetsSheetIdIndexRoute
  AuthSheetsSheetIdOverviewIndexRoute: typeof AuthSheetsSheetIdOverviewIndexRoute
  AuthSheetsSheetIdOverviewCategoryIdEditRoute: typeof AuthSheetsSheetIdOverviewCategoryIdEditRoute
  AuthSheetsSheetIdOverviewCategoryIdIndexRoute: typeof AuthSheetsSheetIdOverviewCategoryIdIndexRoute
}

const AuthSheetsSheetIdRouteChildren: AuthSheetsSheetIdRouteChildren = {
  AuthSheetsSheetIdSettingsRoute: AuthSheetsSheetIdSettingsRoute,
  AuthSheetsSheetIdTransactionFormRoute: AuthSheetsSheetIdTransactionFormRoute,
  AuthSheetsSheetIdIndexRoute: AuthSheetsSheetIdIndexRoute,
  AuthSheetsSheetIdOverviewIndexRoute: AuthSheetsSheetIdOverviewIndexRoute,
  AuthSheetsSheetIdOverviewCategoryIdEditRoute:
    AuthSheetsSheetIdOverviewCategoryIdEditRoute,
  AuthSheetsSheetIdOverviewCategoryIdIndexRoute:
    AuthSheetsSheetIdOverviewCategoryIdIndexRoute,
}

const AuthSheetsSheetIdRouteWithChildren =
  AuthSheetsSheetIdRoute._addFileChildren(AuthSheetsSheetIdRouteChildren)

interface AuthRouteChildren {
  AuthSheetsSheetIdRoute: typeof AuthSheetsSheetIdRouteWithChildren
  AuthSheetsIndexRoute: typeof AuthSheetsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSheetsSheetIdRoute: AuthSheetsSheetIdRouteWithChildren,
  AuthSheetsIndexRoute: AuthSheetsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
